### ISSUE TITLE
PHP版 demo  js 报错

### ISSUE THREAD

**Issue by inbjo** [notadd/neditor#29]
环境 Win10 Chrome 63.0.3239.108 (64)
neditor.all.min.js:5 Uncaught TypeError: Cannot read property 'addEventListener' of null
at Object.on (http://127.0.0.1/utf8-php/neditor.all.min.js:5:18095)
at UE.Editor. (http://127.0.0.1/utf8-php/neditor.all.min.js:11:2969)
at UE.Editor.fireEvent (http://127.0.0.1/utf8-php/neditor.all.min.js:5:10909)
at UE.Editor._setup (http://127.0.0.1/utf8-php/neditor.all.min.js:6:23140)
at about:blank:1:576
请修复...

**Comment by weenhall** [comment]
同问，我也出现了这个问题

**Comment by zuohuadong** [comment]
问题已解决

**Comment by weenhall** [comment]
你好，请问是什么原因，需要重新下载新的文件吗
